"""Audit/generate native formatter witnesses from the prior read-only game capture."""
import sys,hashlib,struct,json
from pathlib import Path
sys.path.insert(0,str(Path(__file__).parent/'python-libs'))
import pefile
image=Path(sys.argv[1])
p=pefile.PE(str(image))
assert p.get_data(0x2daad7,5)==bytes.fromhex('e8 54 b8 ff ff')
assert p.get_data(0x2da955,4)==bytes.fromhex('89 44 24 44')
assert p.get_data(0x2da940,7)==bytes.fromhex('8b 84 dd 44 01 00 00')
assert p.get_data(0x2dabdc,5)==bytes.fromhex('e8 3f b9 ff ff')
regions=[('RangeEntry',0x2d6330,0x2d633e),('RangeBody',0x2d633e,0x2d651f),
 ('ActualLoad',0x2da940,0x2da95f),('RangeCaller',0x2daaa5,0x2daae4),
 ('SingleCaller',0x2dab2d,0x2dabe6),('Normalize',0x2db700,0x2db7fd),
 ('Group',0x2dad40,0x2daecc),('SingleEntry',0x2d6520,0x2d6582),
 ('Bank',0x34a0e0,0x34a10f),('Row',0x2d9730,0x2d97d9),
 ('SingleScalarBranches',0x2d6852,0x2d693f),('SingleTemplate',0x2d732e,0x2d7347),
 ('SingleDispatch',0x2d7794,0x2d7810),
 ('PropertyModeCaller',0x2da9bd,0x2da9e4),('PropertyMode',0x36a630,0x36a6ec),
 ('StatEnumerationCaller',0x2da90c,0x2da929),
 ('StatArraySelection',0x2fa071,0x2fa0a3),('StatEntryLayout',0x2fa180,0x2fa1b2)]
out=['// Generated by audit_formatter.py; validate before installing the SDK hook.','#pragma once','#include <cstddef>','namespace FormatterProfile {']
for name,start,end in regions:
    data=p.get_data(start,end-start)
    out += [f'inline constexpr std::size_t {name}Rva=0x{start:x};',f'inline constexpr unsigned char {name}[]={{']
    out += ['    '+','.join(f'0x{x:02x}' for x in data[i:i+16])+',' for i in range(0,len(data),16)]
    out += ['};']
out += ['struct Witness { std::size_t rva; const unsigned char* bytes; std::size_t size; };', 'inline constexpr Witness Witnesses[]={']
out += [f'    {{{name}Rva,{name},sizeof({name})}},' for name,_,_ in regions]
out += ['};','}']
if '--generate' in sys.argv:
    (Path(__file__).parents[1]/'src/formatter_profile.h').write_text('\n'.join(out)+'\n')
print(json.dumps({'source':str(image),'sha256':hashlib.sha256(image.read_bytes()).hexdigest(),
 'range_helper_rva':'0x2d6330','range_return_rva':'0x2daadc','caller_actual_local':'rsp+0x44',
 'actual_value_source':'statList array +0x30 or +0xa8; Core wide entry: stride16; key stat<<32|layer; int32 value +8','witnesses':len(regions),'status':'static proof; live signatures checked at plugin load'},indent=2))
