"""Read-only PE evidence collector. Use a reconstructed, decrypted runtime PE.

python audit_belt.py --image runtime-game.exe --output belt-evidence.json
--header writes admission bytes ONLY after independent ABI review; never use
freshly generated bytes to automatically admit an unknown game patch.
"""
import argparse
import hashlib
import json
import pathlib
import struct

SITES = [
    ("PlaceStored", 0x15F660, 0x24C),
    ("LocalContext", 0x8B2D0, 32),
    ("LocalPlayer", 0x9A480, 32),
    ("UnitInventory", 0x34A360, 32),
    ("FreeBeltSlot", 0x3862D0, 32),
    ("TransferPage", 0x15F8B0, 32),
    ("FinishInteraction", 0x1A0780, 32),
]
MATERIAL_SITES = [
    ("WithdrawOne", 0x159B30, 0x75),
    ("WithdrawWidget", 0x2CF680, 0xD9),
    ("GetBoundItem", 0x2CE900, 8),
    ("HasCounter", 0x46D9A0, 0x14),
    ("PreviousSeason", 0x23B980, 32),
    ("PreviousOwner", 0x46D9C0, 32),
    ("CurrentOwner", 0x46DA50, 32),
    ("FindPanel", 0x846170, 32),
    ("FindChild", 0x856220, 0x7E),
    ("SelectedTab", 0x23AF50, 32),
    ("UnitId", 0x34A330, 32),
    ("ItemCode", 0x36EF50, 32),
    ("LocalContext", 0x8B2D0, 32),
    ("LocalPlayer", 0x9A480, 32),
    ("UnitInventory", 0x34A360, 32),
    ("FreeBeltSlot", 0x3862D0, 32),
    ("UiMode", 0xCE500, 32),
    ("InteractionMode", 0x1C3420, 32),
    ("FinishInteraction", 0x1A0780, 32),
    ("DisplayItemWitness", 0x2CF4A0, 0x68),
    ("BeltWithdrawWitness", 0x2CF88B, 0x72),
]

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image", type=pathlib.Path, required=True)
    parser.add_argument("--output", type=pathlib.Path, required=True)
    parser.add_argument("--header", type=pathlib.Path)
    parser.add_argument("--materials", action="store_true")
    parser.add_argument("--locate-from", type=pathlib.Path,
                        help="Report candidate entry RVAs from old evidence; never generates admission bytes")
    args = parser.parse_args()
    data = args.image.read_bytes()
    pe = struct.unpack_from("<I", data, 0x3C)[0]
    if data[pe:pe+4] != b"PE\0\0":
        raise ValueError("Not a PE image")
    count = struct.unpack_from("<H", data, pe+6)[0]
    size = struct.unpack_from("<H", data, pe+20)[0]
    image_base = struct.unpack_from("<Q", data, pe+24+24)[0]
    sections = []
    for i in range(count):
        p = pe + 24 + size + i*40
        name = data[p:p+8].rstrip(b"\0").decode("ascii", "replace")
        virtual_size, rva, raw_size, raw = struct.unpack_from("<IIII", data, p+8)
        sections.append((name, rva, raw_size, raw))
    if args.locate_from:
        if args.header:
            parser.error("Candidate discovery cannot generate a header")
        old = json.loads(args.locate_from.read_text())
        candidates = []
        for site in old['sites']:
            for width in [16, 8]:
                needle = bytes.fromhex(site['bytes'])[:width]
                matches = []
                for name, rva, n, raw in sections:
                    if name != '.text':
                        continue
                    code = data[raw:raw+n]
                    offset = code.find(needle)
                    while offset >= 0:
                        matches.append(hex(rva+offset))
                        offset = code.find(needle, offset+1)
                candidates.append({'name': site['name'], 'prefix_length': width, 'candidate_rvas': matches})
        args.output.write_text(json.dumps({'image_sha256': hashlib.sha256(data).hexdigest(),
            'warning': 'Candidates only: confirm callers, branches, ABI and transitive callees before admitting.',
            'candidates': candidates}, indent=2)+'\n')
        print('Wrote candidate addresses; no admission bytes changed')
        return
    def read(rva, length):
        for _, start, n, raw in sections:
            if start <= rva and rva+length <= start+n:
                return data[raw+rva-start:raw+rva-start+length]
        raise ValueError(f"RVA {rva:x} not backed by file bytes")
    if read(0x15F660, 11) != bytes.fromhex("40 53 55 56 57 41 57 48 83 EC 60"):
        raise ValueError("Not the reviewed decrypted image: do not generate admission bytes")
    records = [{"name": name, "rva": hex(rva), "va": hex(image_base+rva),
                "length": size, "bytes": read(rva, size).hex(" "),
                "sha256": hashlib.sha256(read(rva, size)).hexdigest()}
               for name, rva, size in (MATERIAL_SITES if args.materials else SITES)]
    refs = []
    for name, start, n, raw in sections:
        if name != ".text":
            continue
        for offset in range(n-4):
            if data[raw+offset] == 0xE8:
                dest = start+offset+5+struct.unpack_from("<i", data, raw+offset+1)[0]
                if dest == (0x159B30 if args.materials else 0x15F660):
                    refs.append(hex(start+offset))
    report = {"image": str(args.image), "sha256": hashlib.sha256(data).hexdigest(),
              "image_base": hex(image_base), "sites": records,
              "candidate_E8_callers_requires_disassembly": refs}
    args.output.write_text(json.dumps(report, indent=2)+"\n")
    if args.header:
        namespace = 'QolMaterials' if args.materials else 'QolBelt'
        contract = 'MATERIALS-NATIVE-CONTRACT.md' if args.materials else 'BELT-NATIVE-CONTRACT.md'
        lines = ["#pragma once", "#include <cstdint>", f"namespace {namespace}::Signatures {{",
                 f"// Reviewed 2026-09-23; source identity and derivation: docs/{contract}.",
                 "struct Site { uint64_t rva; const unsigned char* bytes; uint32_t size; };"]
        for rec in records:
            values = ["0x"+b for b in rec["bytes"].split()]
            lines.append(f'inline constexpr unsigned char {rec["name"]}[] = {{')
            lines.extend("    "+", ".join(values[i:i+16])+"," for i in range(0,len(values),16))
            lines.append("};")
        lines.append("inline constexpr Site All[] = {")
        lines.extend(f'    {{{rec["rva"]}, {rec["name"]}, sizeof({rec["name"]})}},' for rec in records)
        lines.extend(["};", "}"])
        args.header.write_text("\n".join(lines)+"\n")
    print(f"Recorded {len(records)} native sites and {len(refs)} candidate callers")

if __name__ == "__main__":
    main()
