#pragma once
#include <array>
#include <cstddef>
namespace Aim {
// Semantic catalog only, not extracted game records. See SKILL-CATALOG.md.
struct CatalogSkill {
    int id; const char* name; const char* className; const char* review;
    bool snap; bool enabledByDefault;
};
inline constexpr std::array<CatalogSkill,240> SkillCatalog{{
    {6,"Magic Arrow","amazon","directional target; untested",true,false},
    {7,"Fire Arrow","amazon","directional target; untested",true,false},
    {8,"Inner Sight","amazon","self/buff/automatic; keep native",false,false},
    {9,"Critical Strike","amazon","passive; keep native",true,false},
    {10,"Jab","amazon","melee/unit target; untested",true,false},
    {11,"Cold Arrow","amazon","directional target; untested",true,false},
    {12,"Multi Shot","amazon","tested snap aim",true,true},
    {13,"Dodge","amazon","passive; keep native",true,false},
    {14,"Power Strike","amazon","melee/unit target; untested",true,false},
    {15,"Poison Javelin","amazon","directional target; untested",true,false},
    {16,"Exploding Arrow","amazon","directional target; untested",true,false},
    {17,"Slow Missiles","amazon","self/buff/automatic; keep native",false,false},
    {18,"Avoid","amazon","passive; keep native",true,false},
    {19,"Impale","amazon","melee/unit target; untested",true,false},
    {20,"Lightning Bolt","amazon","directional target; untested",true,false},
    {21,"Ice Arrow","amazon","directional target; untested",true,false},
    {22,"Guided Arrow","amazon","tested snap aim",true,true},
    {23,"Penetrate","amazon","passive; keep native",true,false},
    {24,"Charged Strike","amazon","melee/unit target; untested",true,false},
    {25,"Plague Javelin","amazon","directional target; untested",true,false},
    {26,"Strafe","amazon","directional target; untested",true,false},
    {27,"Immolation Arrow","amazon","directional target; untested",true,false},
    {28,"Dopplezon","amazon","summon/placement; untested",false,false},
    {29,"Evade","amazon","passive; keep native",true,false},
    {30,"Fend","amazon","melee/unit target; untested",true,false},
    {31,"Freezing Arrow","amazon","directional target; untested",true,false},
    {32,"Valkyrie","amazon","summon/placement; untested",false,false},
    {33,"Pierce","amazon","passive; keep native",true,false},
    {34,"Lightning Strike","amazon","melee/unit target; untested",true,false},
    {35,"Lightning Fury","amazon","directional target; untested",true,false},
    {36,"Fire Bolt","sorceress","directional target; untested",true,false},
    {37,"Warmth","sorceress","passive; keep native",false,false},
    {38,"Charged Bolt","sorceress","directional target; untested",true,false},
    {39,"Ice Bolt","sorceress","directional target; untested",true,false},
    {40,"Frozen Armor","sorceress","self/buff/automatic; keep native",false,false},
    {41,"Inferno","sorceress","directional target; untested",true,false},
    {42,"Static Field","sorceress","self/buff/automatic; keep native",false,false},
    {43,"Telekinesis","sorceress","native unit/item/object target; untested",true,false},
    {44,"Frost Nova","sorceress","self-centered area; keep native",false,false},
    {45,"Ice Blast","sorceress","directional target; untested",true,false},
    {46,"Blaze","sorceress","self/buff/automatic; keep native",false,false},
    {47,"Fire Ball","sorceress","directional target; untested",true,false},
    {48,"Nova","sorceress","self-centered area; keep native",false,false},
    {49,"Lightning","sorceress","directional target; untested",true,false},
    {50,"Shiver Armor","sorceress","self/buff/automatic; keep native",false,false},
    {51,"Fire Wall","sorceress","tested snap aim",true,true},
    {52,"Enchant","sorceress","self/buff/automatic; keep native",false,false},
    {53,"Chain Lightning","sorceress","directional target; untested",true,false},
    {54,"Teleport","sorceress","tested ground aim",false,true},
    {55,"Glacial Spike","sorceress","directional target; untested",true,false},
    {56,"Meteor","sorceress","tested snap aim",true,true},
    {57,"Thunder Storm","sorceress","self/buff/automatic; keep native",false,false},
    {58,"Energy Shield","sorceress","self/buff/automatic; keep native",false,false},
    {59,"Blizzard","sorceress","tested snap aim",true,true},
    {60,"Chilling Armor","sorceress","self/buff/automatic; keep native",false,false},
    {61,"Fire Mastery","sorceress","passive; keep native",false,false},
    {62,"Hydra","sorceress","tested snap aim",true,true},
    {63,"Lightning Mastery","sorceress","passive; keep native",false,false},
    {64,"Frozen Orb","sorceress","directional target; untested",true,false},
    {65,"Cold Mastery","sorceress","passive; keep native",false,false},
    {66,"Amplify Damage","necromancer","curse/area target; untested",true,false},
    {67,"Teeth","necromancer","tested snap aim",true,true},
    {68,"Bone Armor","necromancer","self/buff/automatic; keep native",false,false},
    {69,"Skeleton Mastery","necromancer","passive; keep native",false,false},
    {70,"Raise Skeleton","necromancer","corpse target; keep native",false,false},
    {71,"Dim Vision","necromancer","curse/area target; untested",true,false},
    {72,"Weaken","necromancer","curse/area target; untested",true,false},
    {73,"Poison Dagger","necromancer","melee/unit target; untested",true,false},
    {74,"Corpse Explosion","necromancer","corpse target; keep native",false,false},
    {75,"Clay Golem","necromancer","summon/placement; untested",false,false},
    {76,"Iron Maiden","necromancer","curse/area target; untested",true,false},
    {77,"Terror","necromancer","curse/area target; untested",true,false},
    {78,"Bone Wall","necromancer","ground placement; untested",false,false},
    {79,"Golem Mastery","necromancer","passive; keep native",false,false},
    {80,"Raise Skeletal Mage","necromancer","corpse target; keep native",false,false},
    {81,"Confuse","necromancer","curse/area target; untested",true,false},
    {82,"Life Tap","necromancer","curse/area target; untested",true,false},
    {83,"Poison Explosion","necromancer","corpse target; keep native",false,false},
    {84,"Bone Spear","necromancer","directional target; untested",true,false},
    {85,"Blood Golem","necromancer","summon/placement; untested",false,false},
    {86,"Attract","necromancer","curse/area target; untested",true,false},
    {87,"Decrepify","necromancer","curse/area target; untested",true,false},
    {88,"Bone Prison","necromancer","summon/placement; untested",false,false},
    {89,"Summon Resist","necromancer","passive; keep native",false,false},
    {90,"Iron Golem","necromancer","summon/placement; untested",false,false},
    {91,"Lower Resist","necromancer","curse/area target; untested",true,false},
    {92,"Poison Nova","necromancer","self-centered area; keep native",false,false},
    {93,"Bone Spirit","necromancer","directional target; untested",true,false},
    {94,"Fire Golem","necromancer","summon/placement; untested",false,false},
    {95,"Revive","necromancer","corpse target; keep native",false,false},
    {96,"Sacrifice","paladin","melee/unit target; untested",true,false},
    {97,"Smite","paladin","melee/unit target; untested",true,false},
    {98,"Might","paladin","aura; keep native",false,false},
    {99,"Prayer","paladin","aura; keep native",false,false},
    {100,"Resist Fire","paladin","aura; keep native",false,false},
    {101,"Holy Bolt","paladin","directional target; untested",true,false},
    {102,"Holy Fire","paladin","aura; keep native",false,false},
    {103,"Thorns","paladin","aura; keep native",false,false},
    {104,"Defiance","paladin","aura; keep native",false,false},
    {105,"Resist Cold","paladin","aura; keep native",false,false},
    {106,"Zeal","paladin","melee/unit target; untested",true,false},
    {107,"Charge","paladin","native behavior; review before enabling",false,false},
    {108,"Blessed Aim","paladin","aura; keep native",false,false},
    {109,"Cleansing","paladin","aura; keep native",false,false},
    {110,"Resist Lightning","paladin","aura; keep native",false,false},
    {111,"Vengeance","paladin","melee/unit target; untested",true,false},
    {112,"Blessed Hammer","paladin","native behavior; review before enabling",false,false},
    {113,"Concentration","paladin","aura; keep native",false,false},
    {114,"Holy Freeze","paladin","aura; keep native",false,false},
    {115,"Vigor","paladin","aura; keep native",false,false},
    {116,"Conversion","paladin","melee/unit target; untested",true,false},
    {117,"Holy Shield","paladin","self/buff/automatic; keep native",false,false},
    {118,"Holy Shock","paladin","aura; keep native",false,false},
    {119,"Sanctuary","paladin","aura; keep native",false,false},
    {120,"Meditation","paladin","aura; keep native",false,false},
    {121,"Fist of the Heavens","paladin","directional target; untested",true,false},
    {122,"Fanaticism","paladin","aura; keep native",false,false},
    {123,"Conviction","paladin","aura; keep native",false,false},
    {124,"Redemption","paladin","aura; keep native",false,false},
    {125,"Salvation","paladin","aura; keep native",false,false},
    {126,"Bash","barbarian","melee/unit target; untested",true,false},
    {127,"Blade Mastery","barbarian","passive; keep native",false,false},
    {128,"Axe Mastery","barbarian","passive; keep native",false,false},
    {129,"Mace Mastery","barbarian","passive; keep native",false,false},
    {130,"Howl","barbarian","self/buff/automatic; keep native",false,false},
    {131,"Find Potion","barbarian","corpse target; keep native",true,false},
    {132,"Leap","barbarian","tested ground aim",false,true},
    {133,"Double Swing","barbarian","melee/unit target; untested",true,false},
    {134,"Pole Arm Mastery","barbarian","passive; keep native",false,false},
    {135,"Throwing Mastery","barbarian","passive; keep native",false,false},
    {136,"Spear Mastery","barbarian","passive; keep native",false,false},
    {137,"Taunt","barbarian","native behavior; review before enabling",false,false},
    {138,"Shout","barbarian","self/buff/automatic; keep native",false,false},
    {139,"Stun","barbarian","melee/unit target; untested",true,false},
    {140,"Double Throw","barbarian","directional target; untested",true,false},
    {141,"Increased Stamina","barbarian","passive; keep native",false,false},
    {142,"Find Item","barbarian","corpse target; keep native",true,false},
    {143,"Leap Attack","barbarian","native behavior; review before enabling",false,false},
    {144,"Concentrate","barbarian","melee/unit target; untested",true,false},
    {145,"Iron Skin","barbarian","passive; keep native",false,false},
    {146,"Battle Cry","barbarian","self/buff/automatic; keep native",false,false},
    {147,"Frenzy","barbarian","melee/unit target; untested",true,false},
    {148,"Increased Speed","barbarian","passive; keep native",false,false},
    {149,"Battle Orders","barbarian","self/buff/automatic; keep native",false,false},
    {150,"Grim Ward","barbarian","corpse target; keep native",true,false},
    {151,"Whirlwind","barbarian","tested snap aim",true,true},
    {152,"Berserk","barbarian","melee/unit target; untested",true,false},
    {153,"Natural Resistance","barbarian","passive; keep native",false,false},
    {154,"War Cry","barbarian","self/buff/automatic; keep native",false,false},
    {155,"Battle Command","barbarian","self/buff/automatic; keep native",false,false},
    {221,"Raven","druid","summon/placement; untested",false,false},
    {222,"Poison Creeper","druid","summon/placement; untested",false,false},
    {223,"Werewolf","druid","self/buff/automatic; keep native",false,false},
    {224,"Lycanthropy","druid","passive; keep native",false,false},
    {225,"Firestorm","druid","directional target; untested",true,false},
    {226,"Oak Sage","druid","summon/placement; untested",false,false},
    {227,"Summon Spirit Wolf","druid","summon/placement; untested",false,false},
    {228,"Werebear","druid","self/buff/automatic; keep native",false,false},
    {229,"Molten Boulder","druid","directional target; untested",true,false},
    {230,"Arctic Blast","druid","directional target; untested",true,false},
    {231,"Carrion Vine","druid","summon/placement; untested",false,false},
    {232,"Feral Rage","druid","melee/unit target; untested",true,false},
    {233,"Maul","druid","melee/unit target; untested",true,false},
    {234,"Fissure","druid","ground placement; untested",true,false},
    {235,"Cyclone Armor","druid","self/buff/automatic; keep native",false,false},
    {236,"Heart of Wolverine","druid","summon/placement; untested",false,false},
    {237,"Summon Dire Wolf","druid","summon/placement; untested",false,false},
    {238,"Rabies","druid","melee/unit target; untested",true,false},
    {239,"Fire Claws","druid","melee/unit target; untested",true,false},
    {240,"Twister","druid","directional target; untested",true,false},
    {241,"Solar Creeper","druid","summon/placement; untested",false,false},
    {242,"Hunger","druid","melee/unit target; untested",true,false},
    {243,"Shock Wave","druid","directional target; untested",true,false},
    {244,"Volcano","druid","ground placement; untested",true,false},
    {245,"Tornado","druid","directional target; untested",true,false},
    {246,"Spirit of Barbs","druid","summon/placement; untested",false,false},
    {247,"Summon Grizzly","druid","summon/placement; untested",false,false},
    {248,"Fury","druid","melee/unit target; untested",true,false},
    {249,"Armageddon","druid","self/buff/automatic; keep native",false,false},
    {250,"Hurricane","druid","self/buff/automatic; keep native",false,false},
    {251,"Fire Blast","assassin","snap placement; untested",true,false},
    {252,"Claw Mastery","assassin","passive; keep native",false,false},
    {253,"Psychic Hammer","assassin","directional target; untested",true,false},
    {254,"Tiger Strike","assassin","melee/unit target; untested",true,false},
    {255,"Dragon Talon","assassin","melee/unit target; untested",true,false},
    {256,"Shock Web","assassin","point/directional target; untested",true,false},
    {257,"Blade Sentinel","assassin","summon/placement; untested",true,false},
    {258,"Burst of Speed","assassin","self/buff/automatic; keep native",false,false},
    {259,"Fists of Fire","assassin","melee/unit target; untested",true,false},
    {260,"Dragon Claw","assassin","melee/unit target; untested",true,false},
    {261,"Charged Bolt Sentry","assassin","summon/placement; untested",true,false},
    {262,"Wake of Fire","assassin","summon/placement; untested",true,false},
    {263,"Weapon Block","assassin","passive; keep native",true,false},
    {264,"Cloak of Shadows","assassin","native behavior; review before enabling",false,false},
    {265,"Cobra Strike","assassin","melee/unit target; untested",true,false},
    {266,"Blade Fury","assassin","directional target; untested",true,false},
    {267,"Fade","assassin","self/buff/automatic; keep native",false,false},
    {268,"Shadow Warrior","assassin","summon/placement; untested",false,false},
    {269,"Claws of Thunder","assassin","melee/unit target; untested",true,false},
    {270,"Dragon Tail","assassin","melee/unit target; untested",true,false},
    {271,"Lightning Sentry","assassin","summon/placement; untested",true,false},
    {272,"Wake of Inferno","assassin","summon/placement; untested",true,false},
    {273,"Mind Blast","assassin","directional target; untested",true,false},
    {274,"Blades of Ice","assassin","melee/unit target; untested",true,false},
    {275,"Dragon Flight","assassin","point/directional target; untested",true,false},
    {276,"Death Sentry","assassin","summon/placement; untested",true,false},
    {277,"Blade Shield","assassin","self/buff/automatic; keep native",false,false},
    {278,"Venom","assassin","self/buff/automatic; keep native",false,false},
    {279,"Shadow Master","assassin","summon/placement; untested",false,false},
    {280,"Phoenix Strike","assassin","melee/unit target; untested",true,false},
    {373,"Summon Goatman","warlock","summon/placement; untested",false,false},
    {374,"Demonic Mastery","warlock","passive; keep native",false,false},
    {375,"Death Mark","warlock","native behavior; review before enabling",false,false},
    {376,"Summon Tainted","warlock","summon/placement; untested",false,false},
    {377,"Summon Defiler","warlock","summon/placement; untested",false,false},
    {378,"Blood Oath","warlock","passive; keep native",false,false},
    {379,"Engorge","warlock","corpse target; keep native",true,false},
    {380,"Blood Boil","warlock","native behavior; review before enabling",false,false},
    {381,"Consume","warlock","native behavior; review before enabling",false,false},
    {382,"Bind Demon","warlock","native behavior; review before enabling",false,false},
    {383,"Levitate","warlock","passive; keep native",false,false},
    {384,"Eldritch Blast","warlock","directional target; untested",true,false},
    {385,"Hex Bane","warlock","native behavior; review before enabling",false,false},
    {386,"Hex Siphon","warlock","native behavior; review before enabling",false,false},
    {387,"Psychic Ward","warlock","native behavior; review before enabling",false,false},
    {388,"Echoing Strike","warlock","directional target; untested",true,false},
    {389,"Hex Purge","warlock","native behavior; review before enabling",false,false},
    {390,"Blade Warp","warlock","point/directional target; untested",false,false},
    {391,"Cleave","warlock","directional target; untested",true,false},
    {392,"Mirrored Blades","warlock","point/directional target; untested",true,false},
    {393,"Sigil of Lethargy","warlock","native behavior; review before enabling",true,false},
    {394,"Ring of Fire","warlock","native behavior; review before enabling",false,false},
    {395,"Miasma Bolt","warlock","directional target; untested",true,false},
    {396,"Sigil of Rancor","warlock","native behavior; review before enabling",true,false},
    {397,"Enhanced Entropy","warlock","passive; keep native",false,false},
    {398,"Flame Wave","warlock","directional target; untested",true,false},
    {399,"Miasma Chains","warlock","directional target; untested",true,false},
    {400,"Sigil of Death","warlock","native behavior; review before enabling",true,false},
    {401,"Apocalypse","warlock","native behavior; review before enabling",false,false},
    {402,"Abyss","warlock","native behavior; review before enabling",false,false},
}};
inline const CatalogSkill* FindCatalogSkill(int id) noexcept {
    for(const auto& skill:SkillCatalog) if(skill.id==id) return &skill;
    return nullptr;
}
inline const char* CatalogSkillName(int id) noexcept {
    const auto* skill=FindCatalogSkill(id);
    return skill?skill->name:"Custom skill";
}
}
